routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\ComponentController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\CitizenController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\RedirectToApp;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

/*Auto Routes*/
$appUrl = rtrim(config('app.url'),'/');
$url = Url();
$parseUrl = parse_url($appUrl);
$tmpAppUrl = explode('/',$appUrl);
$tmpCurUrl = explode('/',$url->current());
$urlParts = array_slice($tmpCurUrl,count($tmpAppUrl));

$projectUrl = '';
$projectUrl = trim($appUrl, '/');
$projectUrl = preg_replace('#^https?://#', '', rtrim($projectUrl,'/'));
$projectUrl = ltrim(str_replace($parseUrl['host'],'',$projectUrl),'/');

$controller = 'HomeController';
$method = 'index';

if(isset($urlParts[0]) && !empty($urlParts[0]))
    $controller = ucfirst($urlParts[0]).'Controller';
if(isset($urlParts[1]))
    $method = $urlParts[1];
$controller = $controller.'@'.$method;
$namespace = 'App\\Http\\Controllers\\';
$admin_namespace = 'App\\Http\\Controllers\\Admin\\';
/*Auto Routes*/

Route::get('/', function () { return view('login'); });
Route::post('/', function () { return view('login'); });

Route::get($projectUrl.'/idplogin', $namespace.'AuthController@idplogin');
Route::get($projectUrl.'/citizen/login', $namespace.'AuthController@citizenLogin')->name('citizenlogin');
Route::get($projectUrl.'/employee/login', $namespace.'AuthController@employeeLogin')->name('employeelogin');
Route::post($projectUrl.'/rdcdauth', $namespace.'AuthController@rdcdAuth')->name('rdcdauth');
Route::post($projectUrl.'/idpauth', $namespace.'AuthController@idpauth');
Route::get($projectUrl.'/idplogout', $namespace.'AuthController@idplogout');

Route::get($projectUrl.'/doptorlogin', $namespace.'AuthController@doptorlogin');
Route::get($projectUrl.'/doptorauth', $namespace.'AuthController@doptorauth');
Route::get($projectUrl.'/doptorlogout', $namespace.'AuthController@doptorlogout');

Route::post($projectUrl.'/ndpotor', $namespace.'NdoptorController@index');

Route::get($projectUrl.'/changeLanguage/{lang}', $namespace.'HomeController@changeLanguage')->middleware('session.user');

Route::get('/home', [$namespace.HomeController::class, 'index'])->name('home');
// Route::get('/beneficiary/profile', [$namespace.BeneficiaryController::class, 'editProfile']);
// Route::resource('/beneficiary', $namespace.BeneficiaryController::class)->only(['index', 'edit', 'update', 'store']);
// Route::get('/employee/edit', [$namespace.EmployeeController::class, 'edit']);
// Route::resource('/employee', $namespace.EmployeeController::class)->only(['index', 'edit', 'update', 'store']);

Route::get('/admin/login', [AuthController::class, 'create'])->name('login');
Route::post('/admin/login', [AuthController::class, 'authenticate']);

Route::prefix('citizen')->name('citizen.')->group(function(){
    Route::middleware(['guest:citizen'])->group(function(){

    });

    Route::middleware(['session.user:citizen'])->group(function(){
        Route::get('/profile', [CitizenController::class, 'editProfile'])->name('edit');
        Route::put('/{id}', [CitizenController::class, 'update'])->name('update');
        Route::resource('/', CitizenController::class)->only(['index', 'store']);
        Route::get('/verify/{component}', [RedirectToApp::class, 'verifyUser'])->name('verify');
    });
});

Route::prefix('employee')->name('employee.')->group(function(){
    Route::middleware(['guest:employee'])->group(function(){

    });

    Route::middleware(['session.user:employee'])->group(function(){
        Route::get('/edit', [EmployeeController::class, 'edit'])->name('edit');
        Route::put('/{id}', [EmployeeController::class, 'update'])->name('update');
        Route::resource('/', EmployeeController::class)->only(['index', 'store']);
        Route::get('/verify/{component}', [RedirectToApp::class, 'verifyUser'])->name('verify');
    });
});


Route::group(['middleware' => 'admin:admin'], function () {

    //Route For Admin User
    Route::group(['prefix' => 'admin'], function () {
        Route::get('/dashboard', [AdminDashboardController::class, 'index']);
        Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');

        Route::resource('/component', ComponentController::class);
        Route::resource('/user', UserController::class);
        //Route::post('/user/export', UserController::class);
        Route::get('/permission', [PermissionController::class, 'index'])->name('permission');
        Route::get('/permission/getPermissionList/{userType}/{userId}', [PermissionController::class, 'getPermissionByUserID']);
        Route::get('/permission/getUserList/{userType}', [PermissionController::class, 'getUserListByType']);
        Route::post('/permission/update-permission', [PermissionController::class, 'updatePermission']);

        // Route::get('/permission', [PermissionController::class, 'index']);
        // Route::get('/permission/add-permission', [PermissionController::class, 'addPermission']);
        // Route::post('/permission/store-permission', [PermissionController::class, 'savePermission']);


    });
});


//Route::any('{all}', $namespace.$controller)->where('all', '.*')->middleware('session.user');

//require __DIR__.'/auth.php';


/*use Illuminate\Support\Facades\Route;

use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BeneficiaryController;

Route::get('/', function () { return view('login'); });
Route::post('/', function () { return view('login'); });

Route::get('/idplogin',[AuthController::class, 'idplogin']);
Route::post('/idpauth',[AuthController::class, 'idpauth']);
Route::get('/idplogout',[AuthController::class, 'idplogout']);

Route::get('/changeLanguage/{lang}', [HomeController::class, 'changeLanguage']);


Route::get('/beneficiary/profile', [BeneficiaryController::class, 'editProfile']);
Route::resource('/beneficiary', BeneficiaryController::class)->only(['index', 'edit', 'update', 'store']);

Route::get('/users/profile', [UserController::class, 'editProfile']);
Route::resource('users', UserController::class)->only(['index', 'edit', 'update']);

Route::get('/dashboard', [HomeController::class, 'index']);


require __DIR__.'/auth.php';
*/

resources/views/partials/mainmenu.blade.php
<div class="sidebar">
    <div class="sidebar-profile">
        <div class="profile-img">
            <img class="user-profile-image" src="{{ $user->photo??asset('assets/img/user-profile-img.png') }}" />
        </div>
        <div class="profile-information">
            <span class="user-name">
                @if(session()->has('employee'))
                    {{  $user->name_bn?? $user->username }}
                @else
                    {{ $user->name??'করিম উদ্দিন' }}</span>
                @endif

            @if (session()->has('citizen'))
                <span class="user-society-name">সুবিধাভোগী পি.এস.কে সমবায় সমিতি</span>
            @endif
            <span class="user-nid"><label for="nid">জাতীয় পরিচয়পত্রঃ </label>{{ $user->nid??'২৩৯৩৮০১৪৩২' }}</span>
            <span class="user-mobile"><label for="mobile">মোবাইলঃ </label>
                @if(session()->has('employee'))
                    {{ $user->personal_mobile ?? '01717789654' }}
                @else
                    {{ $user->mobile ?? '01717789654' }}
                @endif

            </span>
            <span class="user-email"><label for="email">ইমেইলঃ </label>{{ $user->email??'sample@gmail.com' }}</span>
        </div>
    </div>
    <div class="sidebar-menu-container">
        <ul class="main-menu">
            @if (session()->has('employee') || session()->has('citizen'))
                <li class="active">
                    @if(session()->has('employee'))
                        <a href="{{ route('employee.edit', $user->id??'') }}"><span class="icon profile" aria-hidden="true"></span>{{ __('text.profile') }}</a>
                    @elseif(session()->has('citizen'))
                        <a href="{{ route('citizen.edit', $user->id??'') }}"><span class="icon profile" aria-hidden="true"></span>{{ __('text.profile') }}</a>
                    @else
                        <a href="#">
                    @endif
                </li>
                @php
                    $menuItems = Custom::getUserComponents();
                @endphp
                @foreach ($menuItems as $item)
                <li>
                    <a href="{{ url(config('app.url').$user->type.'/verify/'.$item->id) }}"><span class="icon society" aria-hidden="true"></span>{{ $item->title_bn }}</a>
                </li>
                @endforeach
            @endif
            {{-- <li>
                <a href="/"><span class="icon society" aria-hidden="true"></span>আমার সমিতি</a>
            </li> --}}
            {{-- <li>
                <a href="/user"><span class="icon loan" aria-hidden="true"></span></span>আমার ঋণ</a>
            </li>
            <li>
                <a href="/user"><span class="icon training" aria-hidden="true"></span>আমার প্রশিক্ষণ</a>
            </li>
            <li>
                <a href="/user"><span class="icon news" aria-hidden="true"></span>বার্তা এবং ঘোষণা</a>
            </li> --}}
        </ul>
    </div>
</div>

resources/views/partials/topmenu.blade.php
{{-- <div class="header-container"> --}}
    {{-- <div class="header-left">
        <a href="/home" class="logo-wrapper" title="Home">
            <img class="logo" src="{{ asset('assets/img/logo.png') }}">
        </a>
    </div> --}}
    <div class="header-right top-nav">
        <div class="lang-switcher-wrapper">
            <ul class="lang-menu">
                <li><a class="{{ (session()->get('locale') =='en')?'active':'' }}" href="{{URL::to('changeLanguage/en')}}">English</a></li>
                <li><a class="{{ (session()->get('locale') =='bn')?'active':'' }}" href="{{URL::to('changeLanguage/bn')}}">বাংলা</a></li>
            </ul>
        </div>

        <div class="nav-user-wrapper">
            @if (session()->has('citizen') || session()->has('employee'))
                <button href="#" class="nav-user-btn dropdown-btn" title="{{ __('myprofile') }}" type="button">
                    <span class="sr-only">{{ __('myprofile') }}</span>
                    <span class="nav-user-img">
                        <img src="{{ $user->photo??asset('assets/img/user-profile-img.png') }}" alt="{{ $user->name??'' }}">
                    </span>
                </button>
                <ul class="users-item-dropdown nav-user-dropdown dropdown">
                    <li>
                        @if(session()->has('employee'))
                            <a href="../employee/edit">
                        @elseif(session()->has('citizen'))
                            <a href="../citizen/profile">
                        @else
                            <a href="#">
                        @endif
                            <i data-feather="user" aria-hidden="true"></i>
                            <span>{{ __('text.profile') }}</span>
                        </a>
                    </li>
                    <li><a href="##">
                        <i data-feather="settings" aria-hidden="true"></i>
                        <span>{{ __('text.account_settings') }}</span>
                    </a></li>
                    <li>
                        @if(session()->has('employee'))
                            <a class="danger" href="../doptorlogout">
                        @elseif(session()->has('citizen'))
                            <a class="danger" href="../idplogout">
                        @else
                            <form method="POST" action="{{ route('logout') }}">
                                @csrf
                                <a class="danger" href="{{ route('logout') }}" onclick="event.preventDefault(); this.closest('form').submit();">
                        @endif
                                    <i data-feather="log-out" aria-hidden="true"></i>
                                    <span>{{ __('text.logout') }}</span>
                                </a>
                            </form>
                    </li>
                </ul>
            @else
                {{-- <button type="button" class="btn btn-rdcdlogin">
                    <a href="{{ route('rdcdlogin') }}">{{ __('text.login') }}</a>
                </button> --}}
                <div class="rdcdlogin-dropdown">
                    <button type="button" class="btn btn-rdcdlogin dropdown-toggle" data-bs-toggle="dropdown">
                        {{ __('text.login') }}
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ route('citizenlogin') }}">{{ __('text.citizen_login') }}</a></li>
                        <li><a class="dropdown-item" href="{{ route('employeelogin') }}">{{ __('text.employee_login') }}</a></li>
                    </ul>
                </div>
            @endif
        </div>
        <div class="nav-site-switch-wrapper">
            <button class="white-circle-btn dropdown-btn" title="{{ __('text.services_widget') }}" type="button">
                <span class="sr-only">{{ __('text.services_widget') }}</span>
                <span class="icon site-switch-icon active" aria-hidden="true"></span>
            </button>
            <ul class="users-item-dropdown nav-user-dropdown dropdown">
                <li><a href="##">
                    <i data-feather="user" aria-hidden="true"></i>
                    <span>{{ __('text.services_widget') }}</span>
                </a></li>
                <div id="sso-widget"></div>
            </ul>
        </div>
    </div>
{{-- </div> --}}