routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\ComponentController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\CitizenController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\RedirectToApp;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

/*Auto Routes*/
$appUrl = rtrim(config('app.url'),'/');
$url = Url();
$parseUrl = parse_url($appUrl);
$tmpAppUrl = explode('/',$appUrl);
$tmpCurUrl = explode('/',$url->current());
$urlParts = array_slice($tmpCurUrl,count($tmpAppUrl));

$projectUrl = '';
$projectUrl = trim($appUrl, '/');
$projectUrl = preg_replace('#^https?://#', '', rtrim($projectUrl,'/'));
$projectUrl = ltrim(str_replace($parseUrl['host'],'',$projectUrl),'/');

$controller = 'HomeController';
$method = 'index';

if(isset($urlParts[0]) && !empty($urlParts[0]))
    $controller = ucfirst($urlParts[0]).'Controller';
if(isset($urlParts[1]))
    $method = $urlParts[1];
$controller = $controller.'@'.$method;
$namespace = 'App\\Http\\Controllers\\';
$admin_namespace = 'App\\Http\\Controllers\\Admin\\';
/*Auto Routes*/

Route::get('/', function () { return view('login'); });
Route::post('/', function () { return view('login'); });

Route::get($projectUrl.'/idplogin', $namespace.'AuthController@idplogin');
Route::get($projectUrl.'/citizen/login', $namespace.'AuthController@citizenLogin')->name('citizenlogin');
Route::get($projectUrl.'/employee/login', $namespace.'AuthController@employeeLogin')->name('employeelogin');
Route::post($projectUrl.'/rdcdauth', $namespace.'AuthController@rdcdAuth')->name('rdcdauth');
Route::post($projectUrl.'/idpauth', $namespace.'AuthController@idpauth');
Route::get($projectUrl.'/idplogout', $namespace.'AuthController@idplogout');

Route::get($projectUrl.'/doptorlogin', $namespace.'AuthController@doptorlogin');
Route::get($projectUrl.'/doptorauth', $namespace.'AuthController@doptorauth');
Route::get($projectUrl.'/doptorlogout', $namespace.'AuthController@doptorlogout');

Route::post($projectUrl.'/ndpotor', $namespace.'NdoptorController@index');

Route::get($projectUrl.'/changeLanguage/{lang}', $namespace.'HomeController@changeLanguage')->middleware('session.user');

Route::get('/home', [$namespace.HomeController::class, 'index'])->name('home');
// Route::get('/beneficiary/profile', [$namespace.BeneficiaryController::class, 'editProfile']);
// Route::resource('/beneficiary', $namespace.BeneficiaryController::class)->only(['index', 'edit', 'update', 'store']);
// Route::get('/employee/edit', [$namespace.EmployeeController::class, 'edit']);
// Route::resource('/employee', $namespace.EmployeeController::class)->only(['index', 'edit', 'update', 'store']);

Route::get('/admin/login', [AuthController::class, 'create'])->name('login');
Route::post('/admin/login', [AuthController::class, 'authenticate']);

Route::prefix('citizen')->name('citizen.')->group(function(){
    Route::middleware(['guest:citizen'])->group(function(){

    });

    Route::middleware(['session.user:citizen'])->group(function(){
        Route::get('/profile', [CitizenController::class, 'editProfile'])->name('edit');
        Route::put('/{id}', [CitizenController::class, 'update'])->name('update');
        Route::resource('/', CitizenController::class)->only(['index', 'store']);
        Route::get('/verify/{component}', [RedirectToApp::class, 'verifyUser'])->name('verify');
    });
});

Route::prefix('employee')->name('employee.')->group(function(){
    Route::middleware(['guest:employee'])->group(function(){

    });

    Route::middleware(['session.user:employee'])->group(function(){
        Route::get('/edit', [EmployeeController::class, 'edit'])->name('edit');
        Route::put('/{id}', [EmployeeController::class, 'update'])->name('update');
        Route::resource('/', EmployeeController::class)->only(['index', 'store']);
        Route::get('/verify/{component}', [RedirectToApp::class, 'verifyUser'])->name('verify');
    });
});


Route::group(['middleware' => 'admin:admin'], function () {

    //Route For Admin User
    Route::group(['prefix' => 'admin'], function () {
        Route::get('/dashboard', [AdminDashboardController::class, 'index']);
        Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');

        Route::resource('/component', ComponentController::class);
        Route::resource('/user', UserController::class);
        //Route::post('/user/export', UserController::class);
        Route::get('/permission', [PermissionController::class, 'index'])->name('permission');
        Route::get('/permission/getPermissionList/{userType}/{userId}', [PermissionController::class, 'getPermissionByUserID']);
        Route::get('/permission/getUserList/{userType}', [PermissionController::class, 'getUserListByType']);
        Route::post('/permission/update-permission', [PermissionController::class, 'updatePermission']);

        // Route::get('/permission', [PermissionController::class, 'index']);
        // Route::get('/permission/add-permission', [PermissionController::class, 'addPermission']);
        // Route::post('/permission/store-permission', [PermissionController::class, 'savePermission']);


    });
});


//Route::any('{all}', $namespace.$controller)->where('all', '.*')->middleware('session.user');

//require __DIR__.'/auth.php';


/*use Illuminate\Support\Facades\Route;

use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BeneficiaryController;

Route::get('/', function () { return view('login'); });
Route::post('/', function () { return view('login'); });

Route::get('/idplogin',[AuthController::class, 'idplogin']);
Route::post('/idpauth',[AuthController::class, 'idpauth']);
Route::get('/idplogout',[AuthController::class, 'idplogout']);

Route::get('/changeLanguage/{lang}', [HomeController::class, 'changeLanguage']);


Route::get('/beneficiary/profile', [BeneficiaryController::class, 'editProfile']);
Route::resource('/beneficiary', BeneficiaryController::class)->only(['index', 'edit', 'update', 'store']);

Route::get('/users/profile', [UserController::class, 'editProfile']);
Route::resource('users', UserController::class)->only(['index', 'edit', 'update']);

Route::get('/dashboard', [HomeController::class, 'index']);


require __DIR__.'/auth.php';
*/

app/Models/Component.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Component extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'title_bn', 'title_en', 'icon', 'url', 'status'];

    // public function users(){
    //     return $this->belongsToMany(User::class, 'permissions')->withTimestamps();
    // }

    public function users(){
        return $this->morphedByMany(User::class, 'permission');
    }

    public function employees(){
        return $this->morphedByMany(Employee::class, 'permission');
    }

    public function citizens(){
        return $this->morphedByMany(Citizen::class, 'permission');
    }
}

app/Http/Controllers/Admin/ComponentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Component;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
//use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class ComponentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(auth('admin')->check()){
            $components = Component::select('*')->orderBy('id')->get();
        }
        return view('admin.component.index', compact('components'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.component.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required|string|min:3|unique:components,name',
            'title_en' => 'required|string|min:3',
            'title_bn' => 'required|string|min:2',
            'icon' => 'mimes:jpeg,jpg,bmp,png,gif'
        ];

        $messages = [
            'name.required' => 'Component name is required',
            'name.unique' => 'Component name already exist',
            'title_en.required' => 'Component title is required',
            'title_bn.required' => 'Component title is required',
            'icon.mimes' => 'Icon should be in jpeg/png/gif format'
        ];

        $validatedData = Validator::make($request->all(), $rules, $messages);

        if($validatedData->fails()) {
            return redirect()->back()->withErrors($validatedData->messages())->withInput();
        }

        $data = $request->all();
        $data['icon'] = $request->icon ? $request->file('icon')->getClientOriginalName():'';

        $filename = null;
        if($request->hasFile('icon')){
            $path = public_path().'/images/components';
            if (!is_dir($path)) {
                Storage::makeDirectory($path);
            }

            $filename = $request->file('icon')->getClientOriginalName();
            $request->file('icon')->move($path, $filename);
        }

        if(Component::create($data)){
            return redirect('admin/component')->with('success', 'Item details has been added');
        }
        return redirect()->back()->withInput();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Component  $component
     * @return \Illuminate\Http\Response
     */
    public function show(Component $component)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Component  $component
     * @return \Illuminate\Http\Response
     */
    public function edit(Component $component)
    {
        return view('admin.component.edit', compact('component'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Component  $component
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Component $component)
    {
        $rules = [
            'name' => ['required','string','min:3', Rule::unique('components')->ignore($component->id)],
            'title_en' => 'required|string|min:3',
            'title_bn' => 'required|string|min:2',
            'icon' => 'mimes:jpeg,jpg,bmp,png,gif'
        ];

        $messages = [
            'name.required' => 'Component name is required',
            'name.unique' => 'Component name already exist',
            'title_en.required' => 'Component title is required',
            'title_bn.required' => 'Component title is required',
            'icon.mimes' => 'Icon should be in jpeg/png/gif format'
        ];

        $validatedData = Validator::make($request->all(), $rules, $messages);

        if($validatedData->fails()) {
            return redirect()->back()->withErrors($validatedData->messages())->withInput();
        }

        $data = [
            'title_bn' => $request['title_bn'],
            'title_en' => $request['title_en'],
            'name' => $request['name'],
            'url' => $request['url'],
            'status' => $request['status']
        ];

        $data['icon'] = $request->icon ? $request->file('icon')->getClientOriginalName(): $component->icon;

        $filename = null;
        if($request->hasFile('icon')){
            $path = public_path().'/images/components';
            if (!is_dir($path)) {
                Storage::makeDirectory($path);
            }

            $filename = $request->file('icon')->getClientOriginalName();
            $request->file('icon')->move($path, $filename);
        }

        if(Component::where('id', $component->id)->update($data)){
            return redirect('admin/component')->with('success', 'Item details has been updated');
        }
        return redirect()->back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Component  $component
     * @return \Illuminate\Http\Response
     */
    public function destroy(Component $component)
    {
        if($component->delete()){
            if($component->icon){
                if(file_exists(public_path().'/images/components/' .$component->icon))
                    unlink(public_path().'/images/components/'.$component->icon);
            }
        }
        return redirect('admin/component')->with('success', 'component '.$component->name.' has been deleted');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/admin/component/create.blade.php
@extends('layouts.backendapp')
@section('page_title', 'Create New Component')

@section('content')
	<div class="m-content">
		<div class="row">
			<div class="col-md-11">
				<!--begin::Portlet-->
				<div class="m-portlet m-portlet--tab">
					<div class="m-portlet__head">
						<div class="m-portlet__head-caption">
							<div class="m-portlet__head-title">
								<span class="m-portlet__head-icon m--hide">
									<i class="la la-gear"></i>
								</span>
								<h3 class="m-portlet__head-text">
									Create New Component
								</h3>
							</div>
						</div>
					</div>
                    <!--begin::Form-->
					<form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" action="{{ route('component.store') }}" enctype="multipart/form-data" method="POST">
						@csrf
						<div class="m-portlet__body">
							<div class="form-group m-form__group row">
                                <div class="col-lg-6">
                                    <label for="title_bn">Title (Bengali) <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control m-input{{ $errors->has('title_bn')? ' border-danger' : '' }}" name="title_bn" id="title_bn" aria-describedby="title_bn" value="{{ old('title_bn') }}" placeholder="Enter title in bengali">
                                    @error('title_bn')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="col-lg-6">
                                    <label for="title_en">Title (English) <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control m-input{{ $errors->has('title_en')? ' border-danger' : '' }}" name="title_en" id="title_en" aria-describedby="title_en" value="{{ old('title_en') }}" placeholder="Enter title in english">
                                    @error('title_en')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
							</div>

                            <div class="form-group m-form__group row">
                                <div class="col-lg-6">
                                    <label for="name">Name (English) <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control m-input{{ $errors->has('name')? ' border-danger' : '' }}" name="name" id="name" aria-describedby="name" value="{{ old('name') }}" placeholder="Enter name in english">
                                    @error('name')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="col-lg-6">
                                    <label for="url">Component Path</label>
                                    <input type="text" class="form-control m-input{{ $errors->has('url')? ' border-danger' : '' }}" name="url" id="url" aria-describedby="url" value="{{ old('url') }}" placeholder="Enter path">
                                    @error('url')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                            </div>

							<div class="form-group m-form__group row">
                                <div class="col-lg-6">
                                    <label for="icon">Component Icon</label>
                                    <input type="file" class="form-control-file m-input{{ $errors->has('icon')? ' border-danger' : '' }}" id="icon" name="icon" value="">
                                    @error('icon')
                                        <span class="file-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="col-lg-6">
                                    <label for="status">Status <span class="text-danger">*</span></label>
                                    {!! Form::select('status', ['active'=>'Active', 'inactive'=>'Inactive'], 'active', ['class' => 'form-control', 'id' => 'status', 'placeholder' => 'Select status']) !!}
                                    @error('status')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
							</div>
						</div>
						<div class="m-portlet__foot m-portlet__foot--fit">
							<div class="m-form__actions">
								<button type="submit" class="btn btn-form-submit">
									Submit
								</button>
								<a href="{{ route('component.index') }}" class="btn btn-secondary">Cancel</a>
							</div>
						</div>
					</form>
					<!--end::Form-->
				</div>
				<!--end::Portlet-->
			</div>
		</div>
	</div>

    @section('scripts')
    <script>

    </script>
	@stop

@endsection

resources/views/admin/component/edit.blade.php
@extends('layouts.backendapp')
@section('page_title', 'Update Component')

@section('content')
	<div class="m-content">
		<div class="row">
			<div class="col-md-11">
				<!--begin::Portlet-->
				<div class="m-portlet m-portlet--tab">
					<div class="m-portlet__head">
						<div class="m-portlet__head-caption">
							<div class="m-portlet__head-title">
								<span class="m-portlet__head-icon m--hide">
									<i class="la la-gear"></i>
								</span>
								<h3 class="m-portlet__head-text">
									Update Component
								</h3>
							</div>
						</div>
					</div>
                    <!--begin::Form-->
					<form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" action="{{ route('component.update', $component->id) }}" enctype="multipart/form-data" method="POST">
						@csrf
                        @method('PUT')
						<div class="m-portlet__body">
							<div class="form-group m-form__group row">
                                <div class="col-lg-6">
                                    <label for="title_bn">Title (Bengali) <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control m-input{{ $errors->has('title_bn')? ' border-danger' : '' }}" name="title_bn" id="title_bn" aria-describedby="title_bn" value="{{ old('title_bn')?? $component->title_bn }}" placeholder="Enter title in bengali">
                                    @error('title_bn')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="col-lg-6">
                                    <label for="title_en">Title (English) <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control m-input{{ $errors->has('title_en')? ' border-danger' : '' }}" name="title_en" id="title_en" aria-describedby="title_en" value="{{ old('title_en')?? $component->title_en }}" placeholder="Enter title in english">
                                    @error('title_en')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
							</div>

                            <div class="form-group m-form__group row">
                                <div class="col-lg-6">
                                    <label for="name">Name (English) <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control m-input{{ $errors->has('name')? ' border-danger' : '' }}" name="name" id="name" aria-describedby="name" value="{{ old('name')?? $component->name }}" placeholder="Enter name in english">
                                    @error('name')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="col-lg-6">
                                    <label for="url">Component Path</label>
                                    <input type="text" class="form-control m-input{{ $errors->has('url')? ' border-danger' : '' }}" name="url" id="url" aria-describedby="url" value="{{ old('url')?? $component->url }}" placeholder="Enter path">
                                    @error('url')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                            </div>

							<div class="form-group m-form__group row">
                                <div class="col-lg-6">
                                    <label for="icon">Component Icon</label>
                                    <input type="file" class="form-control-file edit-file-width m-input{{ $errors->has('icon')? ' border-danger' : '' }}" id="icon" name="icon" value="">
                                    @if (file_exists('images/components/'. $component->icon))
                                        <img class="img-align-right" src="/images/components/{{$component->icon}}" alt="{{ $component->title_en }}">
                                    @endif

                                    @error('icon')
                                        <span class="file-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="col-lg-6">
                                    <label for="status">Status <span class="text-danger">*</span></label>
                                    {!! Form::select('status', ['active'=>'Active', 'inactive'=>'Inactive'], $component->status, ['class' => 'form-control', 'id' => 'status', 'placeholder' => 'Select status']) !!}
                                    @error('status')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
							</div>
						</div>
						<div class="m-portlet__foot m-portlet__foot--fit">
							<div class="m-form__actions">
								<button type="submit" class="btn btn-form-submit">
									Submit
								</button>
								<a href="{{ route('component.index') }}" class="btn btn-secondary">Cancel</a>
							</div>
						</div>
					</form>
					<!--end::Form-->
				</div>
				<!--end::Portlet-->
			</div>
		</div>
	</div>

    @section('scripts')
    <script>

    </script>
	@stop

@endsection

resources/views/admin/component/index.blade.php
@extends('layouts.backendapp')

@section('page_title', 'Component List')

@section('content')
	<div class="m-content">
		<div class="m-portlet m-portlet--mobile">
			<div class="m-portlet__head">
				<div class="m-portlet__head-caption">
					<div class="m-portlet__head-title">
						<h3 class="m-portlet__head-text">
							Component List
						</h3>
					</div>
				</div>
			</div>
			<div class="m-portlet__body">
				<!--begin: Search Form -->
				<div class="row">
                    <div class="col-xl-8 col-lg-8">
                        <div class="m-separator m-separator--dashed d-xl-none"></div>
                    </div>
                    <div class="col-xl-4 col-lg-8 new-item-btn-container">
                        <a href="{{ route('component.create') }}" class="btn btn-new-item">
                            <span>
                                <i class="fa fa-plus" aria-hidden="true"></i>
                                <span>
                                    New Component
                                </span>
                            </span>
                        </a>
                    </div>
                </div>
				<!--end: Search Form -->
				<!--begin: Datatable -->
                 <div class="table-responsive">
                    <table class="table table-bordered table-striped align-middle" id="ajax_data">
                        <thead>
                            <tr>
                                <th class="text-center">Id</th>
                                <th>Name</th>
                                <th>Title (English)</th>
                                <th>Title (Bengali)</th>
                                <th class="text-center">Component Icon</th>
                                <th class="text-center">URL</th>
                                <th class="text-center">Create</th>
                                <th width="120" class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if ($components)
                                @foreach ($components as $component)
                                <tr>
                                    <td class="text-center">{{ $component->id }}</td>
                                    <td>{{ $component->name }}</td>
                                    <td>{{ $component->title_en }}</td>
                                    <td>{{ $component->title_bn }}</td>
                                    <td class="text-center">
                                        @if ($component->icon)
                                            <img style="max-width: 25px; max-height:25px" src="/images/components/{{$component->icon}}" alt="{{ $component->title_en }}">
                                        @else
                                            <img src="/images/components/defalt.png" alt="{{ $component->title_en }}">
                                        @endif
                                    </td>
                                    <td class="text-center">{{ $component->url }}</td>
                                    <td class="text-center">{{ $component->created_at }}</td>
                                    <td class="text-center">
                                        <a href="{{ route('component.edit', $component->id) }}"><i class="fa fa-pencil-square-o fa-1x" aria-hidden="true"></i>&nbsp;&nbsp;</a>
                                        <form method="POST" style="display: inline" action="{{ route('component.destroy', $component->id) }}">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{ route('component.destroy', $component->id) }}" onclick="event.preventDefault(); this.closest('form').submit();"><i class="fa fa-times fa-1x" aria-hidden="true"></i></a>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="6">{{ __("There is no component available") }}</td>
                                </tr>
                            @endif
                        </tbody>
                    </table>
                </div>
				<!--end: Datatable -->
			</div>
		</div>
	</div>

   	@section('scripts')

    <script>
		// $(document.body).on('click', '.btn-delete' ,function(){
		// 	var id = $(this).attr('data-id');

		// 	swal({
		// 		title:"Are You Sure?",
		// 		text:"You cannot undo this action!",
		// 		icon:"error",
		// 		confirmButtonText:"<span><i class='la la-trash'></i><span>Yes, Delete it!</span></span>",
		// 		confirmButtonClass:"btn btn-danger m-btn m-btn--pill m-btn--air m-btn--icon",
		// 		showCancelButton:!0,
		// 		cancelButtonText:"<span></i><span>Cancel</span></span>",
		// 		cancelButtonClass:"btn btn-secondary m-btn m-btn--pill m-btn--icon"
		// 	}).then((confirm) => {
		// 		if (confirm.value) {
		// 			$('#deleteForm-'+id).submit();
		// 		}
		// 	});
		// });
		// DatatableJsonRemoteDemo.init()
	//});
    </script>

	@stop
@endsection