routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\ComponentController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\CitizenController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\RedirectToApp;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

/*Auto Routes*/
$appUrl = rtrim(config('app.url'),'/');
$url = Url();
$parseUrl = parse_url($appUrl);
$tmpAppUrl = explode('/',$appUrl);
$tmpCurUrl = explode('/',$url->current());
$urlParts = array_slice($tmpCurUrl,count($tmpAppUrl));

$projectUrl = '';
$projectUrl = trim($appUrl, '/');
$projectUrl = preg_replace('#^https?://#', '', rtrim($projectUrl,'/'));
$projectUrl = ltrim(str_replace($parseUrl['host'],'',$projectUrl),'/');

$controller = 'HomeController';
$method = 'index';

if(isset($urlParts[0]) && !empty($urlParts[0]))
    $controller = ucfirst($urlParts[0]).'Controller';
if(isset($urlParts[1]))
    $method = $urlParts[1];
$controller = $controller.'@'.$method;
$namespace = 'App\\Http\\Controllers\\';
$admin_namespace = 'App\\Http\\Controllers\\Admin\\';
/*Auto Routes*/

Route::get('/', function () { return view('login'); });
Route::post('/', function () { return view('login'); });

Route::get($projectUrl.'/idplogin', $namespace.'AuthController@idplogin');
Route::get($projectUrl.'/citizen/login', $namespace.'AuthController@citizenLogin')->name('citizenlogin');
Route::get($projectUrl.'/employee/login', $namespace.'AuthController@employeeLogin')->name('employeelogin');
Route::post($projectUrl.'/rdcdauth', $namespace.'AuthController@rdcdAuth')->name('rdcdauth');
Route::post($projectUrl.'/idpauth', $namespace.'AuthController@idpauth');
Route::get($projectUrl.'/idplogout', $namespace.'AuthController@idplogout');

Route::get($projectUrl.'/doptorlogin', $namespace.'AuthController@doptorlogin');
Route::get($projectUrl.'/doptorauth', $namespace.'AuthController@doptorauth');
Route::get($projectUrl.'/doptorlogout', $namespace.'AuthController@doptorlogout');

Route::post($projectUrl.'/ndpotor', $namespace.'NdoptorController@index');

Route::get($projectUrl.'/changeLanguage/{lang}', $namespace.'HomeController@changeLanguage')->middleware('session.user');

Route::get('/home', [$namespace.HomeController::class, 'index'])->name('home');
// Route::get('/beneficiary/profile', [$namespace.BeneficiaryController::class, 'editProfile']);
// Route::resource('/beneficiary', $namespace.BeneficiaryController::class)->only(['index', 'edit', 'update', 'store']);
// Route::get('/employee/edit', [$namespace.EmployeeController::class, 'edit']);
// Route::resource('/employee', $namespace.EmployeeController::class)->only(['index', 'edit', 'update', 'store']);

Route::get('/admin/login', [AuthController::class, 'create'])->name('login');
Route::post('/admin/login', [AuthController::class, 'authenticate']);

Route::prefix('citizen')->name('citizen.')->group(function(){
    Route::middleware(['guest:citizen'])->group(function(){

    });

    Route::middleware(['session.user:citizen'])->group(function(){
        Route::get('/profile', [CitizenController::class, 'editProfile'])->name('edit');
        Route::put('/{id}', [CitizenController::class, 'update'])->name('update');
        Route::resource('/', CitizenController::class)->only(['index', 'store']);
        Route::get('/verify/{component}', [RedirectToApp::class, 'verifyUser'])->name('verify');
    });
});

Route::prefix('employee')->name('employee.')->group(function(){
    Route::middleware(['guest:employee'])->group(function(){

    });

    Route::middleware(['session.user:employee'])->group(function(){
        Route::get('/edit', [EmployeeController::class, 'edit'])->name('edit');
        Route::put('/{id}', [EmployeeController::class, 'update'])->name('update');
        Route::resource('/', EmployeeController::class)->only(['index', 'store']);
        Route::get('/verify/{component}', [RedirectToApp::class, 'verifyUser'])->name('verify');
    });
});


Route::group(['middleware' => 'admin:admin'], function () {

    //Route For Admin User
    Route::group(['prefix' => 'admin'], function () {
        Route::get('/dashboard', [AdminDashboardController::class, 'index']);
        Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');

        Route::resource('/component', ComponentController::class);
        Route::resource('/user', UserController::class);
        //Route::post('/user/export', UserController::class);
        Route::get('/permission', [PermissionController::class, 'index'])->name('permission');
        Route::get('/permission/getPermissionList/{userType}/{userId}', [PermissionController::class, 'getPermissionByUserID']);
        Route::get('/permission/getUserList/{userType}', [PermissionController::class, 'getUserListByType']);
        Route::post('/permission/update-permission', [PermissionController::class, 'updatePermission']);

        // Route::get('/permission', [PermissionController::class, 'index']);
        // Route::get('/permission/add-permission', [PermissionController::class, 'addPermission']);
        // Route::post('/permission/store-permission', [PermissionController::class, 'savePermission']);


    });
});


//Route::any('{all}', $namespace.$controller)->where('all', '.*')->middleware('session.user');

//require __DIR__.'/auth.php';


/*use Illuminate\Support\Facades\Route;

use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BeneficiaryController;

Route::get('/', function () { return view('login'); });
Route::post('/', function () { return view('login'); });

Route::get('/idplogin',[AuthController::class, 'idplogin']);
Route::post('/idpauth',[AuthController::class, 'idpauth']);
Route::get('/idplogout',[AuthController::class, 'idplogout']);

Route::get('/changeLanguage/{lang}', [HomeController::class, 'changeLanguage']);


Route::get('/beneficiary/profile', [BeneficiaryController::class, 'editProfile']);
Route::resource('/beneficiary', BeneficiaryController::class)->only(['index', 'edit', 'update', 'store']);

Route::get('/users/profile', [UserController::class, 'editProfile']);
Route::resource('users', UserController::class)->only(['index', 'edit', 'update']);

Route::get('/dashboard', [HomeController::class, 'index']);


require __DIR__.'/auth.php';
*/

resources/views/admin/partials/mainmenu.blade.php
<div class="sidebar">
    <div class="sidebar-menu-container">
        <ul class="main-menu">
            <li>
                <a href="{{ route('user.index') }}"><i class="fa fa-user-circle-o" aria-hidden="true"></i>
                    {{ __('text.user') }}
                </a>
            </li>
            <li>
                <a href="{{ route('component.index') }}"><i class="fa fa-list" aria-hidden="true"></i>
                    {{ __('text.component_list') }}
                </a>
            </li>
            <li>
                <a href="{{ route('permission') }}"><i class="fa fa-list" aria-hidden="true"></i>
                    {{ __('text.assign_permission') }}
                </a>
            </li>
            {{-- <li>
                <a href="/"><span class="icon ecommerce" aria-hidden="true"></span>আমার ই-কমার্স</a>
            </li>
            <li>
                <a href="/"><span class="icon society" aria-hidden="true"></span>আমার সমিতি</a>
            </li>
            <li>
                <a href="/user"><span class="icon loan" aria-hidden="true"></span></span>আমার ঋণ</a>
            </li>
            <li>
                <a href="/user"><span class="icon training" aria-hidden="true"></span>আমার প্রশিক্ষণ</a>
            </li> --}}
        </ul>
    </div>
</div>

resources/views/admin/partials/topmenu.blade.php
<div class="header-container">
    <div class="header-left">
        <a href="/admin/dashboard" class="logo-wrapper" title="Home">
            <span class="icon logo" aria-hidden="true"></span>
        </a>
    </div>
    <div class="header-right top-nav">
        <div class="lang-switcher-wrapper">
            <ul class="lang-menu">
                <li><a class="{{ (session()->get('locale') =='en')?'active':'' }}" href="{{URL::to('changeLanguage/en')}}">English</a></li>
                <li><a class="{{ (session()->get('locale') =='bn')?'active':'' }}" href="{{URL::to('changeLanguage/bn')}}">বাংলা</a></li>
            </ul>
        </div>
        <div class="notification-wrapper">
            <button class="gray-circle-btn dropdown-btn" title="{{ __('text.notification') }}" type="button">
                <span class="sr-only">{{ __('text.user_notification') }}</span>
                <span class="icon notification active" aria-hidden="true"></span>
            </button>
            <ul class="users-item-dropdown notification-dropdown dropdown">
                <li>
                    <a href="##">
                        <div class="notification-dropdown-icon info">
                            <i data-feather="check" aria-hidden="true"></i>
                        </div>
                        <div class="notification-dropdown-text">
                            <span class="notification-dropdown__title">{{ __('text.user_notification') }}</span>
                            <span class="notification-dropdown__subtitle">{{ __('text.no_notification') }}</span>
                        </div>
                    </a>
                </li>
                <li>
                    <a class="link-to-page" href="##">Go to Notifications page</a>
                </li>
            </ul>
        </div>
        <div class="nav-user-wrapper">
            <button href="#" class="nav-user-btn dropdown-btn" title="{{ __('text.myprofile') }}" type="button">
                <span class="sr-only">{{ __('text.myprofile') }}</span>
                <span class="nav-user-img">
                    {{-- <img class="user-profile-image" src="{{ $user->photo??asset('assets/img/user-profile-img.png') }}" /> --}}
                    <img src="{{ $user->photo??asset('assets/img/user-profile-img.png') }}" alt="{{ $user->name??'' }}">
                </span>
            </button>
            <ul class="users-item-dropdown nav-user-dropdown dropdown">
                <li><a href="##">
                    <i data-feather="settings" aria-hidden="true"></i>
                    <span>{{ __('text.account_settings') }}</span>
                </a></li>
                <li>
                    @if(auth('admin')->check())
                    <form method="POST" action="{{ route('logout') }}">
                        @csrf
                        <a class="danger" href="{{ route('logout') }}" onclick="event.preventDefault(); this.closest('form').submit();">
                            <i data-feather="log-out" aria-hidden="true"></i>
                            <span>{{ __('text.logout') }}</span>
                        </a>
                    </form>
                    @else
                        <a class="danger" href="../doptorlogout">
                            <i data-feather="log-out" aria-hidden="true"></i>
                            <span>{{ __('text.logout') }}</span>
                        </a>
                    @endif
                </li>
            </ul>
        </div>
        {{-- <div class="nav-site-switch-wrapper">
            <button class="white-circle-btn dropdown-btn" title="{{ __('text.services_widget') }}" type="button">
                <span class="sr-only">{{ __('text.services_widget') }}</span>
                <span class="icon site-switch-icon active" aria-hidden="true"></span>
            </button>
            <ul class="users-item-dropdown nav-user-dropdown dropdown">
                <li><a href="##">
                    <i data-feather="user" aria-hidden="true"></i>
                    <span>{{ __('text.services_widget') }}</span>
                </a></li>
                <div id="sso-widget"></div>
            </ul>
        </div> --}}
    </div>
</div>