routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\ComponentController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\CitizenController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\RedirectToApp;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

/*Auto Routes*/
$appUrl = rtrim(config('app.url'),'/');
$url = Url();
$parseUrl = parse_url($appUrl);
$tmpAppUrl = explode('/',$appUrl);
$tmpCurUrl = explode('/',$url->current());
$urlParts = array_slice($tmpCurUrl,count($tmpAppUrl));

$projectUrl = '';
$projectUrl = trim($appUrl, '/');
$projectUrl = preg_replace('#^https?://#', '', rtrim($projectUrl,'/'));
$projectUrl = ltrim(str_replace($parseUrl['host'],'',$projectUrl),'/');

$controller = 'HomeController';
$method = 'index';

if(isset($urlParts[0]) && !empty($urlParts[0]))
    $controller = ucfirst($urlParts[0]).'Controller';
if(isset($urlParts[1]))
    $method = $urlParts[1];
$controller = $controller.'@'.$method;
$namespace = 'App\\Http\\Controllers\\';
$admin_namespace = 'App\\Http\\Controllers\\Admin\\';
/*Auto Routes*/

Route::get('/', function () { return view('login'); });
Route::post('/', function () { return view('login'); });

Route::get($projectUrl.'/idplogin', $namespace.'AuthController@idplogin');
Route::get($projectUrl.'/citizen/login', $namespace.'AuthController@citizenLogin')->name('citizenlogin');
Route::get($projectUrl.'/employee/login', $namespace.'AuthController@employeeLogin')->name('employeelogin');
Route::post($projectUrl.'/rdcdauth', $namespace.'AuthController@rdcdAuth')->name('rdcdauth');
Route::post($projectUrl.'/idpauth', $namespace.'AuthController@idpauth');
Route::get($projectUrl.'/idplogout', $namespace.'AuthController@idplogout');

Route::get($projectUrl.'/doptorlogin', $namespace.'AuthController@doptorlogin');
Route::get($projectUrl.'/doptorauth', $namespace.'AuthController@doptorauth');
Route::get($projectUrl.'/doptorlogout', $namespace.'AuthController@doptorlogout');

Route::post($projectUrl.'/ndpotor', $namespace.'NdoptorController@index');

Route::get($projectUrl.'/changeLanguage/{lang}', $namespace.'HomeController@changeLanguage')->middleware('session.user');

Route::get('/home', [$namespace.HomeController::class, 'index'])->name('home');
// Route::get('/beneficiary/profile', [$namespace.BeneficiaryController::class, 'editProfile']);
// Route::resource('/beneficiary', $namespace.BeneficiaryController::class)->only(['index', 'edit', 'update', 'store']);
// Route::get('/employee/edit', [$namespace.EmployeeController::class, 'edit']);
// Route::resource('/employee', $namespace.EmployeeController::class)->only(['index', 'edit', 'update', 'store']);

Route::get('/admin/login', [AuthController::class, 'create'])->name('login');
Route::post('/admin/login', [AuthController::class, 'authenticate']);

Route::prefix('citizen')->name('citizen.')->group(function(){
    Route::middleware(['guest:citizen'])->group(function(){

    });

    Route::middleware(['session.user:citizen'])->group(function(){
        Route::get('/profile', [CitizenController::class, 'editProfile'])->name('edit');
        Route::put('/{id}', [CitizenController::class, 'update'])->name('update');
        Route::resource('/', CitizenController::class)->only(['index', 'store']);
        Route::get('/verify/{component}', [RedirectToApp::class, 'verifyUser'])->name('verify');
    });
});

Route::prefix('employee')->name('employee.')->group(function(){
    Route::middleware(['guest:employee'])->group(function(){

    });

    Route::middleware(['session.user:employee'])->group(function(){
        Route::get('/edit', [EmployeeController::class, 'edit'])->name('edit');
        Route::put('/{id}', [EmployeeController::class, 'update'])->name('update');
        Route::resource('/', EmployeeController::class)->only(['index', 'store']);
        Route::get('/verify/{component}', [RedirectToApp::class, 'verifyUser'])->name('verify');
    });
});


Route::group(['middleware' => 'admin:admin'], function () {

    //Route For Admin User
    Route::group(['prefix' => 'admin'], function () {
        Route::get('/dashboard', [AdminDashboardController::class, 'index']);
        Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');

        Route::resource('/component', ComponentController::class);
        Route::resource('/user', UserController::class);
        //Route::post('/user/export', UserController::class);
        Route::get('/permission', [PermissionController::class, 'index'])->name('permission');
        Route::get('/permission/getPermissionList/{userType}/{userId}', [PermissionController::class, 'getPermissionByUserID']);
        Route::get('/permission/getUserList/{userType}', [PermissionController::class, 'getUserListByType']);
        Route::post('/permission/update-permission', [PermissionController::class, 'updatePermission']);

        // Route::get('/permission', [PermissionController::class, 'index']);
        // Route::get('/permission/add-permission', [PermissionController::class, 'addPermission']);
        // Route::post('/permission/store-permission', [PermissionController::class, 'savePermission']);


    });
});


//Route::any('{all}', $namespace.$controller)->where('all', '.*')->middleware('session.user');

//require __DIR__.'/auth.php';


/*use Illuminate\Support\Facades\Route;

use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BeneficiaryController;

Route::get('/', function () { return view('login'); });
Route::post('/', function () { return view('login'); });

Route::get('/idplogin',[AuthController::class, 'idplogin']);
Route::post('/idpauth',[AuthController::class, 'idpauth']);
Route::get('/idplogout',[AuthController::class, 'idplogout']);

Route::get('/changeLanguage/{lang}', [HomeController::class, 'changeLanguage']);


Route::get('/beneficiary/profile', [BeneficiaryController::class, 'editProfile']);
Route::resource('/beneficiary', BeneficiaryController::class)->only(['index', 'edit', 'update', 'store']);

Route::get('/users/profile', [UserController::class, 'editProfile']);
Route::resource('users', UserController::class)->only(['index', 'edit', 'update']);

Route::get('/dashboard', [HomeController::class, 'index']);


require __DIR__.'/auth.php';
*/

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    // public function components(){
    //     return $this->belongsToMany(Component::class, 'permissions')
    //                 ->withPivot('user_type')
    //                 ->withTimestamps();
    // }

    public function components(){
        return $this->morphToMany(Component::class, 'permission')
                    ->withTimestamps();
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name', 'name_bn', 'email', 'mobile', 'password', 'status'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Hash;
use Yajra\DataTables\DataTables;

class UserController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->ajax()) {
            $data = User::latest()->get();
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row){
                    $actionBtn = '<a href="user/'.$row->id.'/edit" class="btn-edit"><i class="fa fa-pencil-square-o fa-1x" aria-hidden="true"></i></a>
                                  <form style="display:inline" id="deleteForm-'.$row->id.'" action="admin/user/'.$row->id.'" method="POST"><a href="javascript:void(0)" data-id="'.$row->id.'"><i class="fa fa-times fa-1x" aria-hidden="true"></i></a></form>';
                                //<a href="javascript:void(0)" data-id="'.$row->id.'" class="btn-delete"><i class="fa fa-times fa-1x" aria-hidden="true"></i></a>';
                                //@method("delete") @csrf
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('admin.user.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required|string',
            'name_bn' => 'required|string',
            'email' => 'required|email|unique:users',
            'mobile' => 'numeric',
            'status' => 'required|string',
            'password' => 'required|min:6,max:15',
        ];

        $messages = [
            'name.required' => 'User is required',
            'name.string' => 'User name must be a string',
            'name_bn.required' => 'User is required',
            'name_bn.string' => 'User name must be a string',
            'email.required' => 'Email is required',
            'email.email' => 'Email must be a valid email',
            'email.unique' => 'Email must be a unique',
            'mobile.numeric' => 'Mobile should be numeric',
            'status.required' => 'User status is required',
            'password.required' => 'Password is required',
            'password.min' => 'Password length should be between 6 to 15 characters',
        ];

        $validatedData = Validator::make($request->all(), $rules, $messages);

        if($validatedData->fails()) {
            return redirect()->back()->withErrors($validatedData->messages())->withInput();
        }

        $data = $request->all();
        $data['photo'] = $request->photo ? $request->file('photo')->getClientOriginalName() : '';
        $data['password'] = Hash::make($request->password);

        if(User::Create($data)){
            if($request->hasFile('photo')){
                $path = public_path().'/images/users';
                if(!is_dir($path)){
                    Storage::makeDirectory($path);
                }
                $filename = $request->file('photo')->getClientOriginalName();
                $request->file('photo')->move($path, $filename);
            }
            return redirect('admin/user')->with('success', 'New user has been created');
        }
        return redirect()->back()->withInput();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('admin/user/edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'name' => 'required|string',
            'name_bn' => 'required|string',
            'email' => 'required|email',
            'mobile' => 'numeric',
            'status' => 'required|string',
        ];

        $messages = [
            'name.required' => 'User is required',
            'name.string' => 'User name must be a string',
            'name_bn.required' => 'User is required',
            'name_bn.string' => 'User name must be a string',
            'email.required' => 'Email is required',
            'email.email' => 'Email must be a valid email',
            //'email.unique' => 'Email must be a unique',
            'mobile.numeric' => 'Mobile should be numeric',
            'status.required' => 'User status is required',
        ];

        $validatedData = Validator::make($request->all(), $rules, $messages);

        if($validatedData->fails()) {
            return redirect()->back()->withErrors($validatedData->messages())->withInput();
        }

        $data['name'] = $request->name;
        $data['name_bn'] = $request->name_bn;
        $data['email'] = $request->email;
        $data['mobile'] = $request->mobile;
        $data['status'] = $request->status;
        $data['photo'] = $request->photo ? $request->file('photo')->getClientOriginalName() : $request->photo;
        $data['password'] = Hash::make($request->password);

        if(User::where('id', $id)->update($data)){

            if($request->hasFile('photo')){
                $path = public_path().'/images/users';
                if(!is_dir($path)){
                    Storage::makeDirectory($path);
                }
                $filename = $request->file('photo')->getClientOriginalName();
                $request->file('photo')->move($path, $filename);
            }
            return redirect('admin/user')->with('success', 'User information has been updated');
        }
        return redirect()->back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);

        if($user->delete()){
            if($user->photo){
                if(file_exists(public_path().'/images/users/' .$user->photo))
                    unlink(public_path().'/images/users/'.$user->photo);
            }
        }
        return redirect('admin/user')->with('success', 'User '.$user->name.' has been deleted');
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.backendapp')
@section('page_title', 'Create New User')

@section('content')
	<div class="m-content">
		<div class="row">
			<div class="col-lg-8 col-md-10">
				<!--begin::Portlet-->
				<div class="m-portlet m-portlet--tab">
					<div class="m-portlet__head">
						<div class="m-portlet__head-caption">
							<div class="m-portlet__head-title">
								<span class="m-portlet__head-icon m--hide">
									<i class="la la-gear"></i>
								</span>
								<h3 class="m-portlet__head-text">
									Create New User
								</h3>
							</div>
						</div>
					</div>
                    <!--begin::Form-->
					<form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" action="{{ route('user.store') }}" enctype="multipart/form-data" method="POST">
						@csrf
						<div class="m-portlet__body">
							<div class="form-group m-form__group row">
                                <div class="col-lg-6">
                                    <label for="name">Name (English) <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control m-input{{ $errors->has('name')? ' border-danger' : '' }}" name="name" id="name" value="{{ old('name') }}" placeholder="Enter name in english">
                                    @error('name')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="col-lg-6">
                                    <label for="name_bn">Name (Bengali) <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control m-input{{ $errors->has('name_bn')? ' border-danger' : '' }}" name="name_bn" id="name_bn" value="{{ old('name_bn') }}" placeholder="Enter name in bengali">
                                    @error('name_bn')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
							</div>

                            <div class="form-group m-form__group row">
                                <div class="col-lg-6">
                                    <label for="email">Email <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control m-input{{ $errors->has('email')? ' border-danger' : '' }}" name="email" id="email" value="{{ old('email') }}" placeholder="Enter email">
                                    @error('email')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="col-lg-6">
                                    <label for="mobile">Mobile</label>
                                    <input type="text" class="form-control m-input{{ $errors->has('mobile')? ' border-danger' : '' }}" name="mobile" id="mobile" value="{{ old('mobile') }}" placeholder="Enter mobile number">
                                    @error('mobile')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group m-form__group row">
                                <div class="col-lg-6">
                                    <label for="photo">Profile Photo</label>
                                    <input type="file" class="form-control-file m-input{{ $errors->has('photo')? ' border-danger' : '' }}" id="photo" name="photo" value="">
                                    @error('photo')
                                        <span class="file-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="col-lg-6">

                                </div>
                            </div>

							<div class="form-group m-form__group row">
                                <div class="col-lg-6">
                                    <label for="status">Status <span class="text-danger">*</span></label>
                                    {!! Form::select('status', ['active'=>'Active', 'inactive'=>'Inactive'], 'active', ['class' => 'form-control', 'id' => 'status', 'placeholder' => 'Select status']) !!}
                                    @error('status')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="col-lg-6">
                                    <label for="password">Password <span class="text-danger">*</span></label>
                                    <input type="password" name="password" class="form-control m-input{{ $errors->has('password')? ' border-danger' : '' }}">
                                    @error('password')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
							</div>
						</div>
						<div class="m-portlet__foot m-portlet__foot--fit">
							<div class="m-form__actions">
								<button type="submit" class="btn btn-primary">
									Submit
								</button>
								<a href="{{ route('user.index') }}" class="btn btn-secondary">Cancel</a>
							</div>
						</div>
					</form>
					<!--end::Form-->
				</div>
				<!--end::Portlet-->
			</div>
		</div>
	</div>

    @section('scripts')
    <script>

    </script>
	@stop

@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.backendapp')
@section('page_title', 'Create New User')

@section('content')
	<div class="m-content">
		<div class="row">
			<div class="col-lg-8 col-md-10">
				<!--begin::Portlet-->
				<div class="m-portlet m-portlet--tab">
					<div class="m-portlet__head">
						<div class="m-portlet__head-caption">
							<div class="m-portlet__head-title">
								<span class="m-portlet__head-icon m--hide">
									<i class="la la-gear"></i>
								</span>
								<h3 class="m-portlet__head-text">
									Update User Information
								</h3>
							</div>
						</div>
					</div>
                    <!--begin::Form-->
					<form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" action="{{ route('user.update', $user->id) }}" enctype="multipart/form-data" method="POST">
						@csrf
                        @method('PUT')
						<div class="m-portlet__body">
							<div class="form-group m-form__group row">
                                <div class="col-lg-6">
                                    <label for="name">Name (English) <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control m-input{{ $errors->has('name')? ' border-danger' : '' }}" name="name" id="name" value="{{ old('name')??$user->name }}" placeholder="Enter name in english">
                                    @error('name')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="col-lg-6">
                                    <label for="name_bn">Name (Bengali) <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control m-input{{ $errors->has('name_bn')? ' border-danger' : '' }}" name="name_bn" id="name_bn" value="{{ old('name_bn')??$user->name_bn }}" placeholder="Enter name in bengali">
                                    @error('name_bn')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
							</div>

                            <div class="form-group m-form__group row">
                                <div class="col-lg-6">
                                    <label for="email">Email <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control m-input{{ $errors->has('email')? ' border-danger' : '' }}" name="email" id="email" value="{{ old('email')??$user->email }}" placeholder="Enter email">
                                    @error('email')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="col-lg-6">
                                    <label for="mobile">Mobile</label>
                                    <input type="text" class="form-control m-input{{ $errors->has('mobile')? ' border-danger' : '' }}" name="mobile" id="mobile" value="{{ old('mobile')??$user->mobile }}" placeholder="Enter mobile number">
                                    @error('mobile')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group m-form__group row">
                                <div class="col-lg-6">
                                    <label for="photo">Profile Photo</label>
                                    <input type="file" class="form-control-file m-input{{ $errors->has('photo')? ' border-danger' : '' }}" id="photo" name="photo" value="">
                                    @error('photo')
                                        <span class="file-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="col-lg-6">

                                </div>
                            </div>

							<div class="form-group m-form__group row">
                                <div class="col-lg-6">
                                    <label for="status">Status <span class="text-danger">*</span></label>
                                    {!! Form::select('status', ['active'=>'Active', 'inactive'=>'Inactive'], $user->status, ['class' => 'form-control', 'id' => 'status', 'placeholder' => 'Select status']) !!}
                                    @error('status')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="col-lg-6">
                                    <label for="password">Password <span class="text-danger">*</span></label>
                                    <input type="password" name="password" class="form-control m-input{{ $errors->has('password')? ' border-danger' : '' }}">
                                    @error('password')
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
							</div>
						</div>
						<div class="m-portlet__foot m-portlet__foot--fit">
							<div class="m-form__actions">
								<button type="submit" class="btn btn-primary">
									Submit
								</button>
								<a href="{{ route('user.index') }}" class="btn btn-secondary">Cancel</a>
							</div>
						</div>
					</form>
					<!--end::Form-->
				</div>
				<!--end::Portlet-->
			</div>
		</div>
	</div>

    @section('scripts')
    <script>

    </script>
	@stop

@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.backendapp')

@section('page_title', 'User List')

@section('content')
    @section('styles')

    @stop

    <div class="m-content">
		<div class="m-portlet m-portlet--mobile">
			<div class="m-portlet__head">
				<div class="m-portlet__head-caption">
					<div class="m-portlet__head-title">
						<h3 class="m-portlet__head-text">
							User List
						</h3>
					</div>
				</div>
			</div>
			<div class="m-portlet__body">
				<!--begin: Search Form -->
				<div class="row">
                    <div class="col-xl-8 col-lg-8">
                        <div class="m-separator m-separator--dashed d-xl-none"></div>
                    </div>
                    <div class="col-xl-4 col-lg-8 new-item-btn-container">
                        <a href="{{ route('user.create') }}" class="btn btn-new-item">
                            <span>
                                <i class="fa fa-plus" aria-hidden="true"></i>
                                <span>
                                    New User
                                </span>
                            </span>
                        </a>
                    </div>
                </div>
			    <!--begin: Datatable -->
                <div class="table-responsive">
                    <table class="table table-bordered yajra-datatable">
                        <thead>
                            <tr>
                                <th>SN</th>
                                <th>Name</th>
                                <th>Name(Bengali)</th>
                                <th>Email</th>
                                <th>Mobile</th>
                                <th>Created</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

	@section('scripts')
    <script>
        $(document).ready(function() {
            var table = $('.yajra-datatable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('user.index') }}",
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'name', name: 'name'},
                    {data: 'name_bn', name: 'name_bn'},
                    {data: 'email', name: 'email'},
                    {data: 'mobile', name: 'mobile'},
                    {data: 'created_at', name: 'create'},
                    {
                        data: 'action',
                        name: 'action',
                        orderable: true,
                        searchable: true
                    },
                ]
            });

            $(document.body).on('click', '.btn-delete' ,function(){
                var id = $(this).attr('data-id');

                swal({
                    title:"Are You Sure?",
                    text:"You cannot undo this action!",
                    icon:"error",
                    confirmButtonText:"<span><i class='la la-trash'></i><span>Yes, Delete it!</span></span>",
                    confirmButtonClass:"btn btn-danger m-btn m-btn--pill m-btn--air m-btn--icon",
                    showCancelButton:!0,
                    cancelButtonText:"<span></i><span>Cancel</span></span>",
                    cancelButtonClass:"btn btn-secondary m-btn m-btn--pill m-btn--icon"
                }).then((confirm) => {
                    if (confirm.value) {
                        $('#deleteForm-'+id).submit();
                    }
                });
            });
        });
    </script>
	@stop
@endsection